### ISSUE TITLE
no module named 'websocket'

### ISSUE THREAD

**Issue by photonforge** [sermayoral/ha-samsungtv-encrypted#11]
Hi, Thanks for the component, which is the first to work  consistently with H6400!
I am running 0.106.6, and before updating to 0.107, ran the configuration checker. I got the following error:

> Failed config
>   General Errors: 
>     - Platform error media_player.samsungtv_encrypted - No module named 'websocket'

What could be the issue? is it safe to upgrade?

**Comment by sermayoral** [comment]
It's safe to update Home Assistant. First of all update the component to the last version using HACS and then update Home Assistant. 

I'm using 0.107.6 with no issues :-)
