### ISSUE TITLE
unable to run get-token.py

### ISSUE THREAD

**Issue by mvank** [sermayoral/ha-samsungtv-encrypted#13]
running get-token.py gives following error:

root@hassio:/# ./usr/share/hassio/homeassistant/custom_components/samsungtv_encrypted/get_token.py 
./usr/share/hassio/homeassistant/custom_components/samsungtv_encrypted/get_token.py: line 1: import: command not found
from: can't read /var/mail/PySmartCrypto.pysmartcrypto
./usr/share/hassio/homeassistant/custom_components/samsungtv_encrypted/get_token.py: line 5: syntax error near unexpected token `('
./usr/share/hassio/homeassistant/custom_components/samsungtv_encrypted/get_token.py: line 5: `def main(argv):'

Hassio is running on lxc container within portainer.
what doe i need to change or do i something wrong?

**Comment by sermayoral** [comment]
same as #12
