### ISSUE TITLE
How to add sources?

### ISSUE THREAD

**Issue by photonforge** [sermayoral/ha-samsungtv-encrypted#15]
Is there a way to specify and name active sources which can be toggled via dropdown?

**Comment by sermayoral** [comment]
@photonforge you are getting names like HDMI1, HDM2, ... and you would like to customize these names, for example HDMI1 --> Playstation; HDMI2 --> Raspberry

**Comment by photonforge** [comment]
@sermayoral no, im not getting any source list at all.

**Comment by sermayoral** [comment]
@photonforge I can customize the sources, but if you don't get any source list, it doesn't work.

See #10

**Comment by photonforge** [comment]
oh! So no way to get that feature? my tv model is UA40H6400.

**Comment by tonyp740613** [comment]
Sorry to jump in, I get the source list, is there any way for me to customise the list as you mentioned @sermayoral?

**Comment by sermayoral** [comment]
> 
> 
> oh! So no way to get that feature? my tv model is UA40H6400.

You have the same model as me. You should see sources. Please go to #10, put the logs of the custom in debug (can you see in the thread) and pastebin me the result.

**Comment by sermayoral** [comment]
@tonyp740613 not yet,. But i'm going to do it.

**Comment by photonforge** [comment]
> You have the same model as me. You should see sources. Please go to #10, put the logs of the custom in debug (can you see in the thread) and pastebin me the result.

should i install from the zip file mentioned here or just enable debug logging?

> Please, use the samsungtv_encrypted_202003270202.zip attached above, put the custom in debug mode:
logger:
  default: warning
  logs:
    custom_components.samsungtv_encrypted: debug

**Comment by photonforge** [comment]
> > oh! So no way to get that feature? my tv model is UA40H6400.
> 
> You have the same model as me. You should see sources. Please go to #10, put the logs of the custom in debug (can you see in the thread) and pastebin me the result.

Heres the log. 
https://pastebin.com/ZKz9W6L6

**Comment by sermayoral** [comment]
@photonforge is not the last version. Use samsungtv_encrypted_202003281229.zip and, please, write in #10. We are working in this problem in #10

**Comment by photonforge** [comment]
> @photonforge is not the last version. Use samsungtv_encrypted_202003281229.zip and, please, write in #10. We are working in this problem in #10

oh sorry. will post in #10
