### ISSUE TITLE
help for tv token

### ISSUE THREAD

**Issue by skky88** [sermayoral/ha-samsungtv-encrypted#18]
Good day,
someone can help me to launch get_token.py, I have try to launch it on windows CMD, without success.
I already install on my windows Python platform the follow script:
Crypto
Websockets
AES

But i still receive from windws CMD the follow error:

C:\Users\skky8\Desktop\samsungtv_encrypted>py get_token.py
Traceback (most recent call last):
  File "get_token.py", line 3, in <module>
    from PySmartCrypto.pysmartcrypto import PySmartCrypto
  File "C:\Users\skky8\Desktop\samsungtv_encrypted\PySmartCrypto\pysmartcrypto.py", line 2, in <module>
    from . import crypto
  File "C:\Users\skky8\Desktop\samsungtv_encrypted\PySmartCrypto\crypto.py", line 2, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

Like that crypto isn't correct installed, someone can help me?

**Comment by sermayoral** [comment]
@skky88 you must install pycrypto.
```
pip3 install pycrypto
```

**Comment by skky88** [comment]
Hi @sermayoral , I try your package but I still receive error in windows CMD, I resolve the problem by running direct the Get_token.py inside my HASSIO docker terminal.
I confirm that your extension work perfectly with the HU7500 TV, I will try also on a H4500 TV this evening and I will let you know

**Comment by sermayoral** [comment]
Thanks. Let me know please :-)

**Comment by sermayoral** [comment]
@skky88 have you tried it on a H4500? Is it working?

Please, could you expline your solution in #12 ? Thanks!!

**Comment by skky88** [comment]
Hi @sermayoral, sorry for my late reply, I don't have enough time for testing :-).
Anyway I just config my H4500 TV with your script and I confirm that work perfectly like HU7500, off course we still have problem for torn_on command that not work, but this a problem of this kind of TV (when they are off they switch off them WIFI connection) so no command can work for switch on them.

**Comment by sermayoral** [comment]
Thanks @skky88.

Unfortunatelly turning on doesn't work on encrypted models like our TVs. The only way to do that is using the [custom component HDMI version](https://github.com/sermayoral/ha-samsungtv-encrypted#hdmi-versions)
