### ISSUE TITLE
How use get_token.py ?

### ISSUE THREAD

**Issue by sashadeg** [sermayoral/ha-samsungtv-encrypted#19]
Author, how to use your scripts?
How to run it on HassOS ?
I have orangepi with armbian. I run get_token.py. 
Get:
![2020-04-07_23-38-22](https://user-images.githubusercontent.com/63294695/78706972-6696cb80-7929-11ea-93c4-7e2d386e4e6f.png)

**Comment by rpcaeiro** [comment]
There are some packages missing. The easiest way is to install python on a Windows. Follow this recipe done by KixMan28  https://github.com/sermayoral/ha-samsungtv-encrypted/issues/5#issuecomment-601482275
