### ISSUE TITLE
Feedback UE40JU6050 connected

### ISSUE THREAD

**Issue by S-Przybylski** [sermayoral/ha-samsungtv-encrypted#2]
Dear @sermayoral 
thanks for the Implementation!

I set up an connection to my UE40JU6050 using your custom component. For HA I use the docker based solution. Therefore my only working action was to start the script inside the docker container:
  docker -it homeassistant /bin/bash
Navigated to the script:
  cd /config/custom_components/samsungtv_encrypted
Then I have started the script (two times):
Note: -ip -port doesn't work for me
  python3 get_token.py --ip xx.xx.xx.xx --port 8080
  <break> 
Run a second time to get the message on the display:
  python3 get_token.py --ip xx.xx.xx.xx --port 8080
Entered the PIN in less then a minute! 
Got the token (ctx) and session id

Configured HA media_player  - success

**Comment by sermayoral** [comment]
@S-Przybylski Thanks for your feedback!! 

@Flop2006 you can follow these steps to run in in Hass.io :-)

**Comment by Flop2006** [comment]
@sermayoral thanks for your hint! Unfortunately you cannot access the docker container directly via hass.io.
But I found another solution via the Portainer addon:

Via the hassio Addonstore xou can install the Addon "Portainer". (Note that you have to switch off the protection mode to start the addon).
Once installed and started, you can open the Portainer interface via "open web UI".
To be able to access the "homeassistant" container, it must be deleted from the list of hidden containers under Settings.
Via "containers" and "quick action" you can open the console via "exec console.
Now you have to `cd custom_components/samsungtv_encrypted ` and call the script via 
`python3 get_token.py --ip xx.xx.xx.xx --port 8080` enter the pin and got the token (ctx) and the sessionid!

And it works!

Edit: My TV is an Samsung UE40J6350
