### ISSUE TITLE
Scrape sensor conflict

### ISSUE THREAD

**Issue by karmacop** [sermayoral/ha-samsungtv-encrypted#27]
I have a few scrape sensors set up, for example:
sensor:
  - platform: scrape
    resource: http://192.168.20.1/statswan.cmd
    name: VDSL Received Bytes
    select: "table > tr:nth-child(4) > td:nth-child(3)"
    unit_of_measurement: "Bytes"
    authentication: basic
    username: username
    password: password
    value_template: '{{ value }}'
    scan_interval: 60

When using this integration these sensors no longer work and I get the following error:

Log Details (ERROR)

Logger: homeassistant.components.sensor
Source: components/scrape/sensor.py:135
Integration: Sensor (documentation, issues)
First occurred: 8:11:32 AM (4 occurrences)
Last logged: 8:11:34 AM
scrape: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 135, in update
    value = raw_data.select(self._select)[self._index].text
  File "/usr/local/lib/python3.7/site-packages/bs4/element.py", line 1532, in select
    for candidate in _use_candidate_generator(tag):
  File "/usr/local/lib/python3.7/site-packages/bs4/element.py", line 1493, in recursive_select
    for i in tag.select(next_token, recursive_candidate_generator):
  File "/usr/local/lib/python3.7/site-packages/bs4/element.py", line 1451, in select
    'Only the following pseudo-classes are implemented: nth-of-type.')
NotImplementedError: Only the following pseudo-classes are implemented: nth-of-type.

**Comment by karmacop** [comment]
I should note I'm currently running version 0.109.1
So I guess the conflict is with the requirement of beautifulsoup4==4.6.3 vs home assistant which I believe is using 4.9.0?

**Comment by karmacop** [comment]
manifest.json requirements line to:
"requirements": ["wakeonlan==1.1.6", "beautifulsoup4", "netdisco==2.6.0"]
and it fixed the issue. I'm not sure if this is the correct way to solve the conflict so I'm not raising a PR.

**Comment by sermayoral** [comment]
@karmacop I have looked the official documentation here: https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-requirements-during-development--testing

But I have not found anything about using a requeriment without a version. 

Can anyone ilustrate us about it?
