### ISSUE TITLE
Deprecation notice 

### ISSUE THREAD

**Issue by S-Przybylski** [sermayoral/ha-samsungtv-encrypted#28]
After the installation of 109.x dev and 110 dev I got an deprecation notice:
WARNING (MainThread) [homeassistant.components.media_player] MediaPlayerDevice is deprecated, modify SamsungTVDevice to extend MediaPlayerEntity

I think this was adapted for the original integration in https://github.com/home-assistant/core/pull/34592

Could you please change  "MediaPlayerDevice" into "MediaPlayerEntity" in media_player.py?

**Comment by sermayoral** [comment]
Sure! Thanks!!!

**Comment by S-Przybylski** [comment]
Dear @sermayoral 
could you please publish a new release for hacs 2.6?
Thanks

**Comment by sermayoral** [comment]
@S-Przybylski don't worry, we have a week to publish the release, i'm waiting feedback of other user to release a little bunch of changes. I hope doing it this weekend
