### ISSUE TITLE
Unable to find rep on HACS

### ISSUE THREAD

**Issue by photonforge** [sermayoral/ha-samsungtv-encrypted#3]
Ive searched for the repository on HACS, but am unable to find it. Im using the latest HACS version (0.23.2) on home assistant 0.106.6. How do I install??

**Comment by sermayoral** [comment]
It is not in HACS yet. It is in progress. For more details, see https://github.com/hacs/default/pull/260

**Comment by photonforge** [comment]
> It is not in HACS yet. It is in progress. For more details, see [hacs/default#260](https://github.com/hacs/default/pull/260)

oh ok. will wait.
