### ISSUE TITLE
Problem with getting token

### ISSUE THREAD

**Issue by smarthome3b** [sermayoral/ha-samsungtv-encrypted#31]
Its when i try it with pycharm
![image](https://user-images.githubusercontent.com/62770889/81428285-bce36e00-9164-11ea-870f-c514d0a47630.png)
its when i try it with raspberry
![image](https://user-images.githubusercontent.com/62770889/81428485-fae09200-9164-11ea-88de-7c550f4ec7a8.png)

**Comment by sermayoral** [comment]
@smarthome3b in both cases you have to install pycrypto

```
pip3 install pycrypto
```
