### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Isshin** [sermayoral/ha-samsungtv-encrypted#4]
Hi,

After some trial and installation I was able to run get_token
However I got this error:

`HTTPConnectionPool(host='198.168.68.113', port=8000): Max retries exceeded with url: /socket.io/1/?t=1584254387174 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03CF7D60>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because `connected host has failed to respond'

Any ideas?

**Comment by sermayoral** [comment]
Hi. Review the configuration. H Series used to be in port 8080, not 8000

**Comment by Isshin** [comment]
I specified the port with --port 8080
I was able to get the info using SmartCrypto directly. But why didn't specifying the port work?

**Comment by sermayoral** [comment]
I'm not sure what was your problem. In my case, i specified the port 8080, ti was showed in the log and it worked well. 

The get_token.py file was forked of another project and i have not dived in its code. I cannot help you. Sorry
