### ISSUE TITLE
No module named 'crypto' error

### ISSUE THREAD

**Issue by cmjvisser** [sermayoral/ha-samsungtv-encrypted#52]
Using Home Assistant OS (HassOS 4.13). 

Command 'python3 get_token.py --ip 192.168.x.xxx --port 8080' gives an error: no module named crypto. Uninstall and install (pip install crypto) doesn't solve the problem. Also tried to install pycrypto and pycryptodome instead, but both give an install error (found this possible solution on other topics). 

Any suggestions? 

Trying to connect to a 2015 Samsung JU6400 series.

**Comment by sermayoral** [comment]
Similar to https://github.com/sermayoral/ha-samsungtv-encrypted/issues/23
