### ISSUE TITLE
Select Source no longer available

### ISSUE THREAD

**Issue by staraxis** [sermayoral/ha-samsungtv-encrypted#6]
In version 2.1 the select source is no longer visible on the media player entity and using the select_source service call no longer works either.

Version 1.0 allowed me to see the select source drop down and select between TV and HDMI. Any reason this is no longer available? Happy to help out. Cheers

**Comment by sermayoral** [comment]
@staraxis in this new version the custom should autodiscover the input sources.

Can you show me an screenshot of your media_player card?

**Comment by rpcaeiro** [comment]
Same here. Here is my screenshot:
![C4D58072-1CE9-4E07-9F21-3CC2FDFB7727](https://user-images.githubusercontent.com/33000336/77223946-04804d00-6b59-11ea-8a0a-a112517a90f2.jpeg)

**Comment by sermayoral** [comment]
I suppose you cannot control volume with this slider... Do you???

**Comment by rpcaeiro** [comment]
No, slider doesn’t work.

**Comment by sermayoral** [comment]
The uPNP service are not working for you. Maybe the port 7676 is not right for you.

Can you try an uPNP software to see what port your TV is using for uPNP?. You can see all the services available for your TV as well

In Windows you can use this simple but effective software: https://www.microsoft.com/en-us/p/upnp-analyser/9nblggh69pdn?activetab=pivot:overviewtab#

Remember to launch it while the TV is on!!

**Comment by rpcaeiro** [comment]
Hi Sergio,
Thank you for your care. Yes, the port being used is the 7676:
![image](https://user-images.githubusercontent.com/33000336/77227773-90ef3780-6b7a-11ea-8c12-865f9872292d.png)

**Comment by sermayoral** [comment]
@rpcaeiro we are going to solve your problem. In addition, if in the course we see that the custom can be improved, I will do it :-)

Can I see your urn:schemas-upnp-org:service:RenderingControl:1 card? If its location is different from mine: http://YOUR_TV_IP:7676/smp_15_

![sshot-1](https://user-images.githubusercontent.com/30116095/77232303-7760e680-6ba0-11ea-9191-18f5c88aa47b.jpg)

So I would know which your problem is

**Comment by rpcaeiro** [comment]
Sergio, 
That is a good point, indeed. My is not in the smp_15_, it is in the 19. 
![image](https://user-images.githubusercontent.com/33000336/77232586-d2430f80-6b99-11ea-8523-3bb23f81ded7.png)

**Comment by sermayoral** [comment]
@rpcaeiro Ok, problem detected!!

I have to make some changes in the code. I would like to autodiscover uPNP locations in order to get this working in every possible location.

I hope it is solved soon :-)

**Comment by KixMan28** [comment]
@sermayoral  Hi Sergio! I have just realized that I have the same issue as @rpcaeiro. The select source disappeared from my card. The link you provided above doesn't work for me.

**Comment by staraxis** [comment]
Hi all, sorry for the slow reply. Yes I have the same port as @rpcaeiro for my TV. Thanks for the help @sermayoral this is the first samsung integration that has worked for me after years of searching!

**Comment by meloos** [comment]
Hi there, I have Samsung UE40H6400, and have same problem as above. But I know where the issue is. Besides different Location for GetVolume (smp_15_ here), GetVolume itself doesn't work with NotImplemented error code from TV "api". Hence this part of code: https://github.com/sermayoral/ha-samsungtv-encrypted/blob/master/custom_components/samsungtv_encrypted/media_player.py#L192-L198 is not being called, resulting the issue from thread. Adding dummy volume value, allowing code block to run resulted in populated sources with correct one as selected.

**Comment by KixMan28** [comment]
Hi @meloos! Where would you add the dummy volume value?

**Comment by sermayoral** [comment]
I almost have a solution for this, but i need to check a couple of things.

@rpcaeiro (or someone with this problem). Can you access to this IP from any browser with your TV turned on? In your case it would be http://192.168.1.190:7676/smp_19_

You should get a XML file like this:
```
<root>
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
...
```
Can you paste here all the XML content or can attach the file?

Thanks

**Comment by sermayoral** [comment]
@meloos thanks for the report. 

By the way, for everybody, pull requests are welcome if you think it would improve the custom component :-)

**Comment by KixMan28** [comment]
@sermayoral Here is my XML content:

https://pastebin.com/pMjKiuaZ

**Comment by sermayoral** [comment]
Thanks @KixMan28 

what smp_x_ have you browse? 19?

**Comment by KixMan28** [comment]
> Thanks @KixMan28
> 
> what smp_x_ have you browse? 19?

Yes, 19, as you mentioned above. Should I try something else?

**Comment by sermayoral** [comment]
@KixMan28 its Ok, but 19 is not the good one for you. 

I suspect you have the same smp as me. Could you check against smp_15_ ?

**Comment by KixMan28** [comment]
@sermayoral 
Here you go:

https://pastebin.com/tBJkyfDN

**Comment by sermayoral** [comment]
Thanks @KixMan28 

Last test. Could you check agains smp_16_ ?

**Comment by rpcaeiro** [comment]
> I almost have a solution for this, but i need to check a couple of things.
> 
> @rpcaeiro (or someone with this problem). Can you access to this IP from any browser with your TV turned on? In your case it would be http://192.168.1.190:7676/smp_19_
> 
> You should get a XML file like this:
> 
> ```
> <root>
> <specVersion>
> <major>1</major>
> <minor>0</minor>
> </specVersion>
> <device>
> <deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
> ...
> ```
> 
> Can you paste here all the XML content or can attach the file?
> 
> Thanks

Hi Sergio,
Now I’m really confused. Today I did scan again my tv and guess what, today the service rendering is in smp_11_. Is this normal?
Anyway here is the result:

1 0 urn:schemas-upnp-org:device:MediaRenderer:1 MS_DigitalMediaDeviceClass_DMR_V001 Display.TV.LCD Multimedia.DMR DMR-1.50 [TV] sala Samsung Electronics http://www.samsung.com/sec Samsung TV DMR UE65HU8500 AllShare1.0 http://www.samsung.com/sec 20110517DMR uuid:1e65fb81-008e-1000-9fd9-bc1485142079 JHCPH5RIVH56M image/jpeg 48 48 24 /dmr/icon_SML.jpg image/jpeg 120 120 24 /dmr/icon_LRG.jpg image/png 48 48 24 /dmr/icon_SML.png image/png 120 120 24 /dmr/icon_LRG.png urn:schemas-upnp-org:service:RenderingControl:1 urn:upnp-org:serviceId:RenderingControl /smp_13_ /smp_14_ /smp_12_ urn:schemas-upnp-org:service:ConnectionManager:1 urn:upnp-org:serviceId:ConnectionManager /smp_16_ /smp_17_ /smp_15_ urn:schemas-upnp-org:service:AVTransport:1 urn:upnp-org:serviceId:AVTransport /smp_19_ /smp_20_ /smp_18_ Y2014,WebURIPlayable,SeekTRACK_NR,NavigateInPause VEN_0105&DEV_VD0001

**Comment by KixMan28** [comment]
Here it is the smp_16_:

https://pastebin.com/iLKmEHqq

**Comment by sermayoral** [comment]
@rpcaeiro it's possible.

Your TV assingns smp ports randomly... wow.

Thanks!!

**Comment by sermayoral** [comment]
@rpcaeiro by the way, it's not an XML??? Its a little strange...

**Comment by rpcaeiro** [comment]
> @rpcaeiro by the way, it's not an XML??? Its a little strange...

Sorry, was my phone browser.

**Comment by rpcaeiro** [comment]
> @rpcaeiro it's possible.
> 
> Your TV assingns smp ports randomly... wow.
> 
> Thanks!!

I’m now doing a few more attempts to see if I find any pattern

**Comment by sermayoral** [comment]
> 
> 
> > @rpcaeiro it's possible.
> > Your TV assingns smp ports randomly... wow.
> > Thanks!!
> 
> I’m now doing a few more attempts to see if I find any pattern

@rpcaeiro don't worry, this is not a problem because the new code discover smp ports :-). 

All I need is the XML content well-formed. Thanks!!

**Comment by rpcaeiro** [comment]
> > > @rpcaeiro it's possible.
> > > Your TV assingns smp ports randomly... wow.
> > > Thanks!!
> > 
> > 
> > I’m now doing a few more attempts to see if I find any pattern
> 
> @rpcaeiro don't worry, this is not a problem because the new code discover smp ports :-).
> 
> All I need is the XML content well-formed. Thanks!!

Here it is:

<?xml version="1.0" encoding="ISO-8859-1"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:sec="http://www.sec.co.kr/dlna" xmlns:df="http://schemas.microsoft.com/windows/2008/09/devicefoundation" xmlns:pnpx="http://schemas.microsoft.com/windows/pnpx/2005/11">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
<pnpx:X_compatibleId>MS_DigitalMediaDeviceClass_DMR_V001</pnpx:X_compatibleId>
<df:X_deviceCategory>Display.TV.LCD Multimedia.DMR</df:X_deviceCategory>
<dlna:X_DLNADOC xmlns:dlna="urn:schemas-dlna-org:device-1-0">DMR-1.50</dlna:X_DLNADOC>
<friendlyName>[TV] sala</friendlyName>
<manufacturer>Samsung Electronics</manufacturer>
<manufacturerURL>http://www.samsung.com/sec</manufacturerURL>
<modelDescription>Samsung TV DMR</modelDescription>
<modelName>UE65HU8500</modelName>
<modelNumber>AllShare1.0</modelNumber>
<modelURL>http://www.samsung.com/sec</modelURL>
<serialNumber>20110517DMR</serialNumber>
<UDN>uuid:1e65fb81-008e-1000-9fd9-bc1485142079</UDN>
<sec:deviceID>JHCPH5RIVH56M</sec:deviceID>
<iconList>
<icon>
<mimetype>image/jpeg</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>/dmr/icon_SML.jpg</url>
</icon>
<icon>
<mimetype>image/jpeg</mimetype>
<width>120</width>
<height>120</height>
<depth>24</depth>
<url>/dmr/icon_LRG.jpg</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>/dmr/icon_SML.png</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<width>120</width>
<height>120</height>
<depth>24</depth>
<url>/dmr/icon_LRG.png</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
<controlURL>/smp_13_</controlURL>
<eventSubURL>/smp_14_</eventSubURL>
<SCPDURL>/smp_12_</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<controlURL>/smp_16_</controlURL>
<eventSubURL>/smp_17_</eventSubURL>
<SCPDURL>/smp_15_</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
<serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
<controlURL>/smp_19_</controlURL>
<eventSubURL>/smp_20_</eventSubURL>
<SCPDURL>/smp_18_</SCPDURL>
</service>
</serviceList>
<sec:ProductCap>Y2014,WebURIPlayable,SeekTRACK_NR,NavigateInPause</sec:ProductCap>
<pnpx:X_hardwareId>VEN_0105&DEV_VD0001</pnpx:X_hardwareId>
</device>
</root>

**Comment by sermayoral** [comment]
> 
> 
> Here it is the smp_16_:
> 
> https://pastebin.com/iLKmEHqq

@KixMan28 My suspects are right. You have same smp ports as me. The question is... Why your GetVolume service is not working? 

I will try increasing the timeout a little more in the service call. We will see what happens

**Comment by rpcaeiro** [comment]
> > > @rpcaeiro it's possible.
> > > Your TV assingns smp ports randomly... wow.
> > > Thanks!!
> > 
> > 
> > I’m now doing a few more attempts to see if I find any pattern
> 
> @rpcaeiro don't worry, this is not a problem because the new code discover smp ports :-).
> 
> All I need is the XML content well-formed. Thanks!!








> > > @rpcaeiro it's possible.
> > > Your TV assingns smp ports randomly... wow.
> > > Thanks!!
> > 
> > 
> > I’m now doing a few more attempts to see if I find any pattern
> 
> @rpcaeiro don't worry, this is not a problem because the new code discover smp ports :-).
> 
> All I need is the XML content well-formed. Thanks!!

Here it is

[Edit2.txt](https://github.com/sermayoral/ha-samsungtv-encrypted/files/4374800/Edit2.txt)

**Comment by sermayoral** [comment]
@rpcaeiro now it is correct. Thanks!!

It looks very good. I'm going to make some modifications and the custom will be ready. 

If you want, I can share the custom with new changes here before doing a new release. What do you think?

**Comment by rpcaeiro** [comment]
> @rpcaeiro now it is correct. Thanks!!
> 
> It looks very good. I'm going to make some modifications and the custom will be ready.
> 
> If you want, I can share the custom with new changes here before doing a new release. What do you think?

Great, lets do it. I will be more then glad to help you.

**Comment by KixMan28** [comment]
After several restarts of the HA, now the integration works as supposed: I can see all my sources, and the volume slider works.

**Comment by sermayoral** [comment]
@KixMan28 great!!

@rpcaeiro its done. 

Can you replace your custom_component with this, restart HA and  tell us how it works?

[samsungtv_encrypted.zip](https://github.com/sermayoral/ha-samsungtv-encrypted/files/4375224/samsungtv_encrypted.zip)

**Comment by rpcaeiro** [comment]
@sermayoral ,
You are amazing. All working perfectly. Sound, slide, source, off. Thank you

Muchas y muchas gracias por todo tu trabajo. Un fuerte abrazo. :)

**Comment by sermayoral** [comment]
@rpcaeiro great!!!

So, i'm going to commit the changes and doing a release!

Es un placer @rpcaeiro :-)

**Comment by KixMan28** [comment]
Hi Sergio! Should I try this new version myself?

**Comment by sermayoral** [comment]
@KixMan28 is not necessary. 

I'm going to do a release after some minutes, so if you want, you can update it via HACS :-)

**Comment by rpcaeiro** [comment]
Hi @sermayoral, sorry to bring this again, but my TV is now using smp_7_, which means I can't control the sound using the slider anymore. Not sure if this is the reason but if you could take a look will be awesome.
Thanks
