### ISSUE TITLE
please help with token and session id

### ISSUE THREAD

**Issue by AntoxaSa** [sermayoral/ha-samsungtv-encrypted#64]
AES key: 1bb86249e47b0487ade26cd7adce54e3
AES encrypted: c79ded811c4548426847c9360f17430a6a5ab529fc00f6dfb15d0c628ad23429799e19053e25effd53f1efa7f17200aa094183ef79478d1c3a9a23d07fb758044edbe48c123554a0c11d90beac431f58537f48cae0e5f129f141992e6ca22bede4f65b6f9f02d917d39cff56d427bba9d8db4324f4e8561d373f07cf8fe8a070
AES swapped: 94eb0ede9bdb8075e9b05ea4dfc9ad3dcdb12b9114b00061047879502f80315aa60eabdec6dbed1828553893b02927c1e7a0e44ae1a1d50776c87f326c1b54efa866ec080436c21d601ad47958b72f55f597d10a5c19179aca3d9ef75647add9fbd90f057b15e945d858f8d877c58b2eff9452d78566632ed6eaa9157eb47e48
data buffer: 0000000636353433323194EB0EDE9BDB8075E9B05EA4DFC9AD3DCDB12B9114B00061047879502F80315AA60EABDEC6DBED1828553893B02927C1E7A0E44AE1A1D50776C87F326C1B54EFA866EC080436C21D601AD47958B72F55F597D10A5C19179ACA3D9EF75647ADD9FBD90F057B15E945D858F8D877C58B2EFF9452D78566632ED6EAA9157EB47E48
hash: eaa88a2398e752e753f374ac3c89c83d298fce97
secondStepResponse: {"auth_data":"{\"auth_type\":\"SPC\",\"request_id\":\"0\",\"GeneratorClientHello\":\"010100000000000000009E00000006363534333231C3F8996FF4A7E6FC46FADA953B5CCE0DCE26E0097BFDE0FA6A6A01E030326A59B22ECE0FAE170C286E73CD9B0110350815553036DE58A9BE981F9C55C244C2F085F2A706034A039FA86B8D7FC654D318A904A0CF49D01ACE7DE1E09EE638425165721B5B677C191D912B51DB1144C5C8AE2BD11CD21C34D372F7033EE5B1B0A9E4E3AA064B971F10F8640D8EEA0E6FE59A67F0500000000000\"}"}

thirdLen: 138
hello: 010100000000000000009e00000006363534333231c3f8996ff4a7e6fc46fada953b5cce0dce26e0097bfde0fa6a6a01e030326a59b22ece0fae170c286e73cd9b0110350815553036de58a9be981f9c55c244c2f085f2a706034a039fa86b8d7fc654d318a904a0cf49d01ace7de1e09ee638425165721b5b677c191d912b51db1144c5c8ae2bd11cd21c34d372f7033ee5b1b0a9e4e3aa064b971f10f8640d8eea0e6fe59a67f0500000000000
dest: 00000006363534333231c3f8996ff4a7e6fc46fada953b5cce0dce26e0097bfde0fa6a6a01e030326a59b22ece0fae170c286e73cd9b0110350815553036de58a9be981f9c55c244c2f085f2a706034a039fa86b8d7fc654d318a904a0cf49d01ace7de1e09ee638425165721b5b677c191d912b51db1144c5c8ae2bd11cd21c34d372f7033ee5b1b0a9eaa88a2398e752e753f374ac3c89c83d298fce97
userId: 654321
pEncWBGx: c3f8996ff4a7e6fc46fada953b5cce0dce26e0097bfde0fa6a6a01e030326a59b22ece0fae170c286e73cd9b0110350815553036de58a9be981f9c55c244c2f085f2a706034a039fa86b8d7fc654d318a904a0cf49d01ace7de1e09ee638425165721b5b677c191d912b51db1144c5c8ae2bd11cd21c34d372f7033ee5b1b0a9
pEncGx: 83405627005e06735830f19d4aa560a46e772ea1258f200cd41a530b02dc19991404fd4458ff576750948d47b45140a65850e8529f28dec3cef8afdcc16e71abcb21a6910a2053bb6b798f0ec84bd74f669e90f92f7583a5ac67b2178e897619ccfe94ae29c0309852413774b17dcf91a61aa54915772adc97dd2a6609cb5aee
pGx: 8ebbaa22db84702ba242ad18515a588052f1ce33c21e39653f072b45ddf5a49d67216f7321cdbaf3946b63fd5f98c0e9eb48c2d46ba1e065607a70d76e10570207c225882ac1544adad5ca4bb6f3cc464c532288989098d5fb7739e593ada89ee26dcabaed86800b54b8c39688256478f9e8c8aad0ea1ff23c7310e36fb2ee72
secret: 56bd91a87035072c554fdf771b55903c89e33022b0ec8c0b4b041c6cc4cf73c2e35a729c581a256025d7ba2572b7dc59b14da1e10822d381c8d559d8867a7f042142e2f64b7daa7bb900e8cadd2ad2cec7877b462871c56ab548192310dc15e7894a6264f0571de6caae70004470f5133ed38acef08c715fa42d8b67fde2ed6b
hash2: e4e3aa064b971f10f8640d8eea0e6fe59a67f050
secret2: 36353433323156bd91a87035072c554fdf771b55903c89e33022b0ec8c0b4b041c6cc4cf73c2e35a729c581a256025d7ba2572b7dc59b14da1e10822d381c8d559d8867a7f042142e2f64b7daa7bb900e8cadd2ad2cec7877b462871c56ab548192310dc15e7894a6264f0571de6caae70004470f5133ed38acef08c715fa42d8b67fde2ed6b
hash3: e4e3aa064b971f10f8640d8eea0e6fe59a67f050
Pin OK :)

dest_hash: 648ddd478236564bf1e87ade56ecef59a3064032
SKPrime: cb5960a6d5538f12bca26ca7a4a1b4f533cb929f
SKPrimeHash: 7765ab97c414befc9beeb48e7abe6f198ed7ac28
ctx: 2937351f27f69b84cf8a5f9e9fdfff37
Pin accepted :)
tell me where is the token and session id? what to enter in configuration.yaml?

**Comment by Lee-View** [comment]
Your token is 2937351f27f69b84cf8a5f9e9fdfff37 (ctx: line)
Session ID should be bellow  "Pin accepted :)"

**Comment by sermayoral** [comment]
> Your token is 2937351f27f69b84cf8a5f9e9fdfff37 (ctx: line)
> Session ID should be bellow "Pin accepted :)"

Normally 1 (SessionID)
