### ISSUE TITLE
HA restart breaks the component

### ISSUE THREAD

**Issue by KixMan28** [sermayoral/ha-samsungtv-encrypted#69]
I run HA on a RPi 3B+, with the latest HassOS (5.10), latest Supervisor (2021.02.5 and HA core latest release (core-2021.2.1).
My TV is a Samsung H6400 model

Every time I restart my HA instance or I update my HA, the media player entity becomes unavailable. To bring it back I need to run the get_token.py, to generate a new token.

Is this the normal behavior?

**Comment by sermayoral** [comment]
Hi, sorry for the delay. 

I have the same TV model, and this behaviour doesn't happen to me. 

Still happen?

**Comment by KixMan28** [comment]
Since a week everythin works fine again. I just updated my HA instance to ver 2021.3.1 and the add-on work fine.
