### ISSUE TITLE
Can't control TV: UE48JU6770

### ISSUE THREAD

**Issue by pauldev20** [sermayoral/ha-samsungtv-encrypted#73]
The problem is that sending a command will result in nothing happening. 
Getting a token/session is no problem. After debugging I can see that the script connects via a websocket to the TV successfully. But no matter what command I try to send via `PySmartCrypto().control()` nothing will happen. 
Is there a solution to this problem?

The script I used:
```python
HOST = "<IP>"
PORT = 8080
NAME = "[TV] UE48JU6770 (15_HAWKM_UHD_2D_SC)"
TIMEOUT = 2
MAC = "<MAC>"
UUID = "<UUID>"
TOKEN = "<token>"
SESSION_ID = "1"
KEY_POWER_OFF = "KEY_POWEROFF"
TURN_ON_ACTION = None

DEVICE = SamsungTVDevice(HOST, PORT, NAME, TIMEOUT, MAC, UUID, TOKEN, SESSION_ID, KEY_POWER_OFF, TURN_ON_ACTION)
print(DEVICE.pingTV())
REMOTE = DEVICE.get_remote()
REMOTE.control("KEY_MUTE")
REMOTE.close()
```

**Comment by sermayoral** [comment]
It's possible JU model is not supported... :-(
