### ISSUE TITLE
please add version key

### ISSUE THREAD

**Issue by mantaalex** [sermayoral/ha-samsungtv-encrypted#74]
Logger: homeassistant.loader
Source: loader.py:794
First occurred: 6:43:38 PM (1 occurrences)
Last logged: 6:43:38 PM

No 'version' key in the manifest file for custom integration 'samsungtv_encrypted'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'samsungtv_encrypted'

**Comment by sermayoral** [comment]
This is solved in the 3.6 version
