### ISSUE TITLE
How to resolve the dependency conflict?

### ISSUE THREAD

**Issue by VolnaJ** [sermayoral/ha-samsungtv-encrypted#75]
The logs show an attempt to install netdisco version 2.6.0. The system has a new version of netdisco 2.8.3. The component does not work. How to resolve the dependency conflict?

**Comment by sermayoral** [comment]
@VolnaJ maybe bumping netdisco to 2.8.3 in this custom_component?

**Comment by VolnaJ** [comment]
if I understood you correctly, do you propose to do so? 
`"requirements": ["wakeonlan == 1.1.6", "beautifulsoup4 == 4.6.0", "netdisco == 2.8.3"],`
If yes then I tried so hard

**Comment by sermayoral** [comment]
Yes, please. Try it, and if it works, make a PR ☺️

**Comment by VolnaJ** [comment]
I've already tried changing the version. Wonders :-) The last attempt did not help, I tried again and now the error does not appear.

**Comment by sermayoral** [comment]
@VolnaJ, do you think it's necessary to change the dependency version in the requirements? I'm a little confused of your explanation. Thanks!

**Comment by VolnaJ** [comment]
I replaced the version in the manifest and it worked.

**Comment by sermayoral** [comment]
@VolnaJ, ok, so I'm going to replace in the requirements for the future versions. Thanks
