### ISSUE TITLE
UE50HU6900: Power On not working: Unable to find service kodi.call_method

### ISSUE THREAD

**Issue by torsten2k6** [sermayoral/ha-samsungtv-encrypted#78]
Hi,

the integration works fine for my TV (UE50HU6900), except the Power-On function (when the TV is in standby).

I have also tested it with the turn_on_action in the "configuration.yaml":

    turn_on_action:
        - service: kodi.call_method
          data:
            entity_id: media_player.kodi
            method: Addons.ExecuteAddon
            addonid: script.json-cec
            params:
              command: turn_on 0

But when I try to turn it on, I am receiving the following error:

2021-08-26 21:29:40 ERROR (MainThread) [homeassistant.helpers.script.samsung_tv_remote] Samsung TV Remote: Error executing script. Service not found for call_service at pos 1: Unable to find service kodi.call_method

--> This is somehow "obvious", because I don´t have a kodi integration running. So how is this intended to work?

**Comment by sermayoral** [comment]
@torsten2k6 this component does not have a way of turning on the TV. You should turn on the TV in a external way, such us Kody. If you don't have Kody installed an working, your code doesn't work
