### ISSUE TITLE
Netdisco 2.8.3 conflicts with HA >= 20218.0 which requires 2.9.0

### ISSUE THREAD

**Issue by hogend** [sermayoral/ha-samsungtv-encrypted#79]
Subject says all. Please, update netdisco == 2.8.3 to netdisco >= 2.8.3 since there are no incompatible API chnages

**Comment by sermayoral** [comment]
@hogend feel free to open a Pull Request in order to fix this

**Comment by hogend** [comment]
On Wednesday, 17 November 2021 00:33:47 CET Sergio Mayoral Martínez wrote:
> @hogend feel free to open a Pull Request in order to fix this

Done.

Regards,
Rene

**Comment by sermayoral** [comment]
Fixes in #81
